cc_test(
  name = "concurrent_queue_test",
  size = "small",
  srcs = ["concurrent_queue_test.cc"],
  deps = [
    "@googletest//:gtest",
    "@googletest//:gtest_main",
    "//concurrent:concurrent_queue"
  ],
)