cc_test(
  name = "concurrent_queue_test",
  size = "small",
  srcs = ["concurrent_queue_test.cc"],
  deps = [
    "//concurrent_queue:concurrent_queue",
    "@googletest//:gtest",
    "@googletest//:gtest_main"
  ],
)