load("//bazel:build_system.bzl", "matrix_module", "matrix_module_binary")

matrix_module_binary(
    name = "main",
    srcs = [
        "main.cc",
    ],
    deps = [
        "//concurrent:concurrent_queue"
    ],
)