load("@rules_cc//cc:defs.bzl", "cc_library")

cc_library(
    name = "concurrent_queue",
    hdrs = ["concurrent_queue.h"],
    visibility = [
        "//main:__pkg__",
        "//test:__pkg__"
    ]
)