
load("//bazel:build_system.bzl", "matrix_module")

matrix_module(
    name = "concurrent_queue",
    src = "concurrent_queue.cc",
    visibility = [
        "//main:__pkg__",
        "//test:__pkg__"
    ]
)